Add error when given an invalid option

diff --git a/setup_linters b/setup_linters
--- a/setup_linters
+++ b/setup_linters
@@ -61,4 +61,8 @@ then
   github react-redux
   eslint react-redux
   stylelint react-redux
+else
+then
+  echo "Invalid option. Use the --help flag to checkout all the options."
+  exit 1
 fi
